import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  eslint: {
    ignoreDuringBuilds: true,
  },
  pageExtensions: ["js", "jsx", "ts", "tsx", "md", "mdx"],
  experimental: {
    mdxRs: false,
  },
  images: {
    formats: ["image/avif", "image/webp"],
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    remotePatterns: [
      {
        protocol: "https",
        hostname: "cdn.sanity.io",
      },
      {
        protocol: "https",
        hostname: "images.unsplash.com",
      },
    ],
  },
  async redirects() {
    return [
      // 301 redirects: phantom URLs that 404 → closest real content
      { source: "/odisha/berhampur", destination: "/odisha/bhubaneswar", permanent: true },
      { source: "/odisha/odisha-vs-karnataka", destination: "/odisha/odishas-untapped-potential", permanent: true },
      { source: "/hiring/what-does-executive-search-cost", destination: "/hiring/the-cost-of-a-failed-executive-hire", permanent: true },

      // 301 redirects: /essays/[slug] → /[category]/[slug]
      { source: "/essays/a-love-letter-to-odisha", destination: "/odisha/a-love-letter-to-odisha", permanent: true },
      { source: "/essays/active-waiting", destination: "/philosophy/active-waiting", permanent: true },
      { source: "/essays/ai-and-education", destination: "/future-of-work/ai-and-education", permanent: true },
      { source: "/essays/ai-and-hiring", destination: "/future-of-work/ai-and-hiring", permanent: true },
      { source: "/essays/ai-and-human-potential", destination: "/future-of-work/ai-and-human-potential", permanent: true },
      { source: "/essays/ai-and-india", destination: "/future-of-work/ai-and-india", permanent: true },
      { source: "/essays/ai-and-opportunity", destination: "/opportunity/ai-and-opportunity", permanent: true },
      { source: "/essays/berhampur", destination: "/odisha/berhampur", permanent: true },
      { source: "/essays/beyond-gdp-what-a-developed-odisha-must-be-answerable-for", destination: "/odisha/beyond-gdp-what-a-developed-odisha-must-be-answerable-for", permanent: true },
      { source: "/essays/bhubaneswar", destination: "/odisha/bhubaneswar", permanent: true },
      { source: "/essays/books-that-changed-my-thinking", destination: "/philosophy/books-that-changed-my-thinking", permanent: true },
      { source: "/essays/building-a-global-business-from-odisha", destination: "/odisha/building-a-global-business-from-odisha", permanent: true },
      { source: "/essays/building-for-a-billion-people", destination: "/india/building-for-a-billion-people", permanent: true },
      { source: "/essays/building-from-kalahandi", destination: "/kalahandi/building-from-kalahandi", permanent: true },
      { source: "/essays/building-through-uncertainty", destination: "/entrepreneurship/building-through-uncertainty", permanent: true },
      { source: "/essays/ceo-search", destination: "/hiring/ceo-search", permanent: true },
      { source: "/essays/cfo-search", destination: "/hiring/cfo-search", permanent: true },
      { source: "/essays/chief-of-staff", destination: "/hiring/chief-of-staff", permanent: true },
      { source: "/essays/cmo-search", destination: "/hiring/cmo-search", permanent: true },
      { source: "/essays/compounding-failure-loop", destination: "/frameworks/compounding-failure-loop", permanent: true },
      { source: "/essays/contentment-vs-success", destination: "/philosophy/contentment-vs-success", permanent: true },
      { source: "/essays/cto-recruitment-india", destination: "/hiring/cto-recruitment-india", permanent: true },
      { source: "/essays/cto-search", destination: "/hiring/cto-search", permanent: true },
      { source: "/essays/cuttack", destination: "/odisha/cuttack", permanent: true },
      { source: "/essays/digital-public-infrastructure", destination: "/india/digital-public-infrastructure", permanent: true },
      { source: "/essays/dubai", destination: "/hiring/dubai", permanent: true },
      { source: "/essays/eastern-indias-biopharma-gap", destination: "/odisha/eastern-indias-biopharma-gap", permanent: true },
      { source: "/essays/entrepreneurship-in-kalahandi", destination: "/kalahandi/entrepreneurship-in-kalahandi", permanent: true },
      { source: "/essays/failure-prediction-system", destination: "/frameworks/failure-prediction-system", permanent: true },
      { source: "/essays/fintech-cto-recruitment", destination: "/hiring/fintech-cto-recruitment", permanent: true },
      { source: "/essays/fintech", destination: "/hiring/fintech", permanent: true },
      { source: "/essays/first-generation-founder-framework", destination: "/frameworks/first-generation-founder-framework", permanent: true },
      { source: "/essays/first-generation-professionals-and-opportunity", destination: "/opportunity/first-generation-professionals-and-opportunity", permanent: true },
      { source: "/essays/forty-one-days", destination: "/hiring/forty-one-days", permanent: true },
      { source: "/essays/founder-lessons-from-the-frontline", destination: "/entrepreneurship/founder-lessons-from-the-frontline", permanent: true },
      { source: "/essays/gen-ai-wont-replace-recruiters", destination: "/hiring/gen-ai-wont-replace-recruiters", permanent: true },
      { source: "/essays/geography-advantage-framework", destination: "/frameworks/geography-advantage-framework", permanent: true },
      { source: "/essays/global-talent-how-borders-are-dissolving", destination: "/future-of-work/global-talent-how-borders-are-dissolving", permanent: true },
      { source: "/essays/growing-up-in-an-odia-medium-school", destination: "/kalahandi/growing-up-in-an-odia-medium-school", permanent: true },
      { source: "/essays/growing-up-in-kalahandi", destination: "/kalahandi/growing-up-in-kalahandi", permanent: true },
      { source: "/essays/gtm", destination: "/hiring/gtm", permanent: true },
      { source: "/essays/hackernoon-startup-of-the-year-2023", destination: "/entrepreneurship/hackernoon-startup-of-the-year-2023", permanent: true },
      { source: "/essays/have-they-done-this-before", destination: "/philosophy/have-they-done-this-before", permanent: true },
      { source: "/essays/healthspan-vs-lifespan", destination: "/philosophy/healthspan-vs-lifespan", permanent: true },
      { source: "/essays/hiring-slo-framework", destination: "/frameworks/hiring-slo-framework", permanent: true },
      { source: "/essays/hiring-system-health", destination: "/frameworks/hiring-system-health", permanent: true },
      { source: "/essays/how-4g-changed-india", destination: "/india/how-4g-changed-india", permanent: true },
      { source: "/essays/how-executive-search-works", destination: "/hiring/how-executive-search-works", permanent: true },
      { source: "/essays/how-i-think-about-learning", destination: "/philosophy/how-i-think-about-learning", permanent: true },
      { source: "/essays/how-i-think-about-people", destination: "/philosophy/how-i-think-about-people", permanent: true },
      { source: "/essays/how-i-think-about-systems", destination: "/philosophy/how-i-think-about-systems", permanent: true },
      { source: "/essays/how-long-does-executive-search-take", destination: "/hiring/how-long-does-executive-search-take", permanent: true },
      { source: "/essays/how-opportunity-compounds", destination: "/opportunity/how-opportunity-compounds", permanent: true },
      { source: "/essays/how-to-create-opportunity-for-others", destination: "/opportunity/how-to-create-opportunity-for-others", permanent: true },
      { source: "/essays/how-to-evaluate-executive-candidates", destination: "/hiring/how-to-evaluate-executive-candidates", permanent: true },
      { source: "/essays/how-to-find-cto-india", destination: "/hiring/how-to-find-cto-india", permanent: true },
      { source: "/essays/how-to-write-an-executive-role-brief", destination: "/hiring/how-to-write-an-executive-role-brief", permanent: true },
      { source: "/essays/improving-lives-with-new-opportunities", destination: "/opportunity/improving-lives-with-new-opportunities", permanent: true },
      { source: "/essays/india-vs-china-talent", destination: "/india/india-vs-china-talent", permanent: true },
      { source: "/essays/india", destination: "/hiring/india", permanent: true },
      { source: "/essays/indian-achievers-award-2022", destination: "/entrepreneurship/indian-achievers-award-2022", permanent: true },
      { source: "/essays/indias-ai-opportunity", destination: "/india/indias-ai-opportunity", permanent: true },
      { source: "/essays/indias-future-in-10-years", destination: "/india/indias-future-in-10-years", permanent: true },
      { source: "/essays/indias-greatest-asset-is-its-people", destination: "/india/indias-greatest-asset-is-its-people", permanent: true },
      { source: "/essays/indias-infrastructure-revolution", destination: "/india/indias-infrastructure-revolution", permanent: true },
      { source: "/essays/indias-startup-ecosystem", destination: "/india/indias-startup-ecosystem", permanent: true },
      { source: "/essays/indias-technology-ecosystem", destination: "/india/indias-technology-ecosystem", permanent: true },
      { source: "/essays/intelligence-hiring-system", destination: "/frameworks/intelligence-hiring-system", permanent: true },
      { source: "/essays/intelligence-hiring-vs-traditional-hiring", destination: "/hiring/intelligence-hiring-vs-traditional-hiring", permanent: true },
      { source: "/essays/is-ai-replacing-executive-recruiters", destination: "/hiring/is-ai-replacing-executive-recruiters", permanent: true },
      { source: "/essays/is-bhubaneswar-a-tech-hub", destination: "/odisha/is-bhubaneswar-a-tech-hub", permanent: true },
      { source: "/essays/is-odisha-good-for-startups", destination: "/odisha/is-odisha-good-for-startups", permanent: true },
      { source: "/essays/is-odisha-safe-to-visit", destination: "/odisha/is-odisha-safe-to-visit", permanent: true },
      { source: "/essays/kalahandi-and-the-opportunity-gap", destination: "/kalahandi/kalahandi-and-the-opportunity-gap", permanent: true },
      { source: "/essays/karnataka", destination: "/india/karnataka", permanent: true },
      { source: "/essays/langkawi-the-day-everything-looked-perfect", destination: "/travel/langkawi-the-day-everything-looked-perfect", permanent: true },
      { source: "/essays/learning-from-people", destination: "/philosophy/learning-from-people", permanent: true },
      { source: "/essays/lessons-from-airports", destination: "/travel/lessons-from-airports", permanent: true },
      { source: "/essays/lessons-from-rural-india", destination: "/kalahandi/lessons-from-rural-india", permanent: true },
      { source: "/essays/long-term-thinking-in-a-short-term-world", destination: "/philosophy/long-term-thinking-in-a-short-term-world", permanent: true },
      { source: "/essays/maharashtra", destination: "/india/maharashtra", permanent: true },
      { source: "/essays/mandate-recovery-framework", destination: "/frameworks/mandate-recovery-framework", permanent: true },
      { source: "/essays/midnight-calls-and-invisible-sacrifices", destination: "/philosophy/midnight-calls-and-invisible-sacrifices", permanent: true },
      { source: "/essays/nationalism-vs-patriotism", destination: "/india/nationalism-vs-patriotism", permanent: true },
      { source: "/essays/networks-are-not-networking", destination: "/opportunity/networks-are-not-networking", permanent: true },
      { source: "/essays/odisha-ai-ecosystem", destination: "/odisha/odisha-ai-ecosystem", permanent: true },
      { source: "/essays/odisha-economy", destination: "/odisha/odisha-economy", permanent: true },
      { source: "/essays/odisha-infrastructure", destination: "/odisha/odisha-infrastructure", permanent: true },
      { source: "/essays/odisha-manufacturing", destination: "/odisha/odisha-manufacturing", permanent: true },
      { source: "/essays/odisha-startups", destination: "/odisha/odisha-startups", permanent: true },
      { source: "/essays/odisha-talent", destination: "/odisha/odisha-talent", permanent: true },
      { source: "/essays/odisha-technology-ecosystem", destination: "/odisha/odisha-technology-ecosystem", permanent: true },
      { source: "/essays/odisha-tourism", destination: "/odisha/odisha-tourism", permanent: true },
      { source: "/essays/odisha-transport-vision", destination: "/odisha/odisha-transport-vision", permanent: true },
      { source: "/essays/odisha-vs-gujarat", destination: "/odisha/odisha-vs-gujarat", permanent: true },
      { source: "/essays/odisha-vs-karnataka", destination: "/odisha/odisha-vs-karnataka", permanent: true },
      { source: "/essays/odishas-resource-trap", destination: "/odisha/odishas-resource-trap", permanent: true },
      { source: "/essays/odishas-untapped-potential", destination: "/odisha/odishas-untapped-potential", permanent: true },
      { source: "/essays/on-identity-and-where-you-come-from", destination: "/philosophy/on-identity-and-where-you-come-from", permanent: true },
      { source: "/essays/on-success-what-it-actually-means", destination: "/philosophy/on-success-what-it-actually-means", permanent: true },
      { source: "/essays/one-year-later", destination: "/philosophy/one-year-later", permanent: true },
      { source: "/essays/opportunity-and-mobility-in-modern-india", destination: "/opportunity/opportunity-and-mobility-in-modern-india", permanent: true },
      { source: "/essays/opportunity-changes-lives", destination: "/opportunity/opportunity-changes-lives", permanent: true },
      { source: "/essays/opportunity-framework", destination: "/frameworks/opportunity-framework", permanent: true },
      { source: "/essays/opportunity-gaps", destination: "/opportunity/opportunity-gaps", permanent: true },
      { source: "/essays/opportunity-in-india", destination: "/opportunity/opportunity-in-india", permanent: true },
      { source: "/essays/opportunity-in-rural-india", destination: "/opportunity/opportunity-in-rural-india", permanent: true },
      { source: "/essays/opportunity-mobility-framework", destination: "/frameworks/opportunity-mobility-framework", permanent: true },
      { source: "/essays/people-are-more-similar-than-different", destination: "/philosophy/people-are-more-similar-than-different", permanent: true },
      { source: "/essays/places-that-changed-how-i-think", destination: "/travel/places-that-changed-how-i-think", permanent: true },
      { source: "/essays/questions-i-keep-returning-to", destination: "/philosophy/questions-i-keep-returning-to", permanent: true },
      { source: "/essays/remote-cto-hiring", destination: "/hiring/remote-cto-hiring", permanent: true },
      { source: "/essays/remote-work-and-india", destination: "/india/remote-work-and-india", permanent: true },
      { source: "/essays/remote-work-what-we-know", destination: "/future-of-work/remote-work-what-we-know", permanent: true },
      { source: "/essays/remote", destination: "/hiring/remote", permanent: true },
      { source: "/essays/retained-vs-contingency-search", destination: "/hiring/retained-vs-contingency-search", permanent: true },
      { source: "/essays/rourkela", destination: "/odisha/rourkela", permanent: true },
      { source: "/essays/saas-cto-search", destination: "/hiring/saas-cto-search", permanent: true },
      { source: "/essays/saas", destination: "/hiring/saas", permanent: true },
      { source: "/essays/sales-account-management", destination: "/hiring/sales-account-management", permanent: true },
      { source: "/essays/sambalpur", destination: "/odisha/sambalpur", permanent: true },
      { source: "/essays/showing-friends-around-odisha", destination: "/odisha/showing-friends-around-odisha", permanent: true },
      { source: "/essays/singapore", destination: "/hiring/singapore", permanent: true },
      { source: "/essays/skills-vs-degrees", destination: "/future-of-work/skills-vs-degrees", permanent: true },
      { source: "/essays/state-capacity-is-the-ultimate-competitive-advantage", destination: "/india/state-capacity-is-the-ultimate-competitive-advantage", permanent: true },
      { source: "/essays/stories-from-the-road", destination: "/travel/stories-from-the-road", permanent: true },
      { source: "/essays/strategy-consulting", destination: "/hiring/strategy-consulting", permanent: true },
      { source: "/essays/systems-that-create-opportunity", destination: "/opportunity/systems-that-create-opportunity", permanent: true },
      { source: "/essays/systems-that-destroy-opportunity", destination: "/opportunity/systems-that-destroy-opportunity", permanent: true },
      { source: "/essays/talent-from-small-town-india", destination: "/kalahandi/talent-from-small-town-india", permanent: true },
      { source: "/essays/talent-is-evenly-distributed", destination: "/opportunity/talent-is-evenly-distributed", permanent: true },
      { source: "/essays/talent-signal-framework", destination: "/frameworks/talent-signal-framework", permanent: true },
      { source: "/essays/tamil-nadu", destination: "/india/tamil-nadu", permanent: true },
      { source: "/essays/telangana", destination: "/india/telangana", permanent: true },
      { source: "/essays/the-50-day-executive-search", destination: "/hiring/the-50-day-executive-search", permanent: true },
      { source: "/essays/the-autonomous-hiring-era", destination: "/future-of-work/the-autonomous-hiring-era", permanent: true },
      { source: "/essays/the-childhood-lessons-i-still-use-every-day", destination: "/kalahandi/the-childhood-lessons-i-still-use-every-day", permanent: true },
      { source: "/essays/the-cost-of-hiring-the-wrong-leader", destination: "/hiring/the-cost-of-hiring-the-wrong-leader", permanent: true },
      { source: "/essays/the-evolution-of-my-thinking", destination: "/philosophy/the-evolution-of-my-thinking", permanent: true },
      { source: "/essays/the-first-international-client", destination: "/entrepreneurship/the-first-international-client", permanent: true },
      { source: "/essays/the-four-ways-hiring-infrastructure-fails", destination: "/hiring/the-four-ways-hiring-infrastructure-fails", permanent: true },
      { source: "/essays/the-future-belongs-to-operational-intelligence", destination: "/hiring/the-future-belongs-to-operational-intelligence", permanent: true },
      { source: "/essays/the-future-of-executive-search", destination: "/hiring/the-future-of-executive-search", permanent: true },
      { source: "/essays/the-future-of-indian-cities", destination: "/india/the-future-of-indian-cities", permanent: true },
      { source: "/essays/the-future-of-kalahandi", destination: "/kalahandi/the-future-of-kalahandi", permanent: true },
      { source: "/essays/the-future-of-odisha", destination: "/odisha/the-future-of-odisha", permanent: true },
      { source: "/essays/the-geography-of-opportunity", destination: "/opportunity/the-geography-of-opportunity", permanent: true },
      { source: "/essays/the-india-i-see", destination: "/india/the-india-i-see", permanent: true },
      { source: "/essays/the-information-gap", destination: "/opportunity/the-information-gap", permanent: true },
      { source: "/essays/the-joy-of-growing-something-from-scratch", destination: "/entrepreneurship/the-joy-of-growing-something-from-scratch", permanent: true },
      { source: "/essays/the-kalahandi-most-people-never-see", destination: "/kalahandi/the-kalahandi-most-people-never-see", permanent: true },
      { source: "/essays/the-most-underrated-innovation-in-india", destination: "/india/the-most-underrated-innovation-in-india", permanent: true },
      { source: "/essays/the-next-decade-of-work", destination: "/future-of-work/the-next-decade-of-work", permanent: true },
      { source: "/essays/the-obligation-that-comes-with-getting-through-the-door", destination: "/opportunity/the-obligation-that-comes-with-getting-through-the-door", permanent: true },
      { source: "/essays/the-reality-behind-overnight-success", destination: "/entrepreneurship/the-reality-behind-overnight-success", permanent: true },
      { source: "/essays/the-recruiter-isnt-being-replaced", destination: "/future-of-work/the-recruiter-isnt-being-replaced", permanent: true },
      { source: "/essays/the-rise-of-hiring-system-health", destination: "/hiring/the-rise-of-hiring-system-health", permanent: true },
      { source: "/essays/tier-2-tier-3-cities-india", destination: "/india/tier-2-tier-3-cities-india", permanent: true },
      { source: "/essays/tourism-as-an-economic-engine", destination: "/philosophy/tourism-as-an-economic-engine", permanent: true },
      { source: "/essays/travel-as-a-learning-system", destination: "/travel/travel-as-a-learning-system", permanent: true },
      { source: "/essays/uk", destination: "/hiring/uk", permanent: true },
      { source: "/essays/usa", destination: "/hiring/usa", permanent: true },
      { source: "/essays/vp-engineering-india", destination: "/hiring/vp-engineering-india", permanent: true },
      { source: "/essays/vp-engineering", destination: "/hiring/vp-engineering", permanent: true },
      { source: "/essays/vp-product-search", destination: "/hiring/vp-product-search", permanent: true },
      { source: "/essays/vp-sales-search", destination: "/hiring/vp-sales-search", permanent: true },
      { source: "/essays/web3-leadership-search", destination: "/hiring/web3-leadership-search", permanent: true },
      { source: "/essays/web3", destination: "/hiring/web3", permanent: true },
      { source: "/essays/what-am-i-building", destination: "/entrepreneurship/what-am-i-building", permanent: true },
      { source: "/essays/what-am-i-learning", destination: "/philosophy/what-am-i-learning", permanent: true },
      { source: "/essays/what-automation-cannot-replace", destination: "/future-of-work/what-automation-cannot-replace", permanent: true },
      { source: "/essays/what-changed-my-mind-this-year", destination: "/philosophy/what-changed-my-mind-this-year", permanent: true },
      { source: "/essays/what-does-executive-search-cost", destination: "/hiring/what-does-executive-search-cost", permanent: true },
      { source: "/essays/what-does-travel-teach-you-about-yourself", destination: "/travel/what-does-travel-teach-you-about-yourself", permanent: true },
      { source: "/essays/what-good-policy-actually-looks-like", destination: "/india/what-good-policy-actually-looks-like", permanent: true },
      { source: "/essays/what-home-looks-like-from-far-away", destination: "/travel/what-home-looks-like-from-far-away", permanent: true },
      { source: "/essays/what-i-believe", destination: "/philosophy/what-i-believe", permanent: true },
      { source: "/essays/what-industries-are-growing-in-odisha", destination: "/odisha/what-industries-are-growing-in-odisha", permanent: true },
      { source: "/essays/what-is-kalahandi", destination: "/kalahandi/what-is-kalahandi", permanent: true },
      { source: "/essays/what-is-odisha-known-for", destination: "/odisha/what-is-odisha-known-for", permanent: true },
      { source: "/essays/what-is-opportunity", destination: "/opportunity/what-is-opportunity", permanent: true },
      { source: "/essays/what-is-retained-executive-search", destination: "/hiring/what-is-retained-executive-search", permanent: true },
      { source: "/essays/what-is-the-future-of-bhubaneswar", destination: "/odisha/what-is-the-future-of-bhubaneswar", permanent: true },
      { source: "/essays/what-kalahandi-taught-me-about-human-nature", destination: "/kalahandi/what-kalahandi-taught-me-about-human-nature", permanent: true },
      { source: "/essays/what-kalahandi-taught-me-about-opportunity", destination: "/kalahandi/what-kalahandi-taught-me-about-opportunity", permanent: true },
      { source: "/essays/what-kalahandi-taught-me-about-resilience", destination: "/kalahandi/what-kalahandi-taught-me-about-resilience", permanent: true },
      { source: "/essays/what-kalinga-knew-about-the-indian-ocean", destination: "/odisha/what-kalinga-knew-about-the-indian-ocean", permanent: true },
      { source: "/essays/what-makes-a-great-executive-brief", destination: "/hiring/what-makes-a-great-executive-brief", permanent: true },
      { source: "/essays/what-makes-great-talent-stand-out", destination: "/future-of-work/what-makes-great-talent-stand-out", permanent: true },
      { source: "/essays/what-missed-opportunity-costs", destination: "/opportunity/what-missed-opportunity-costs", permanent: true },
      { source: "/essays/what-odisha-gets-right", destination: "/odisha/what-odisha-gets-right", permanent: true },
      { source: "/essays/what-three-thousand-a-month-in-recruiting-tools-actually-costs-you", destination: "/hiring/what-three-thousand-a-month-in-recruiting-tools-actually-costs-you", permanent: true },
      { source: "/essays/what-to-expect-from-executive-search", destination: "/hiring/what-to-expect-from-executive-search", permanent: true },
      { source: "/essays/what-travel-has-taught-me", destination: "/travel/what-travel-has-taught-me", permanent: true },
      { source: "/essays/what-travel-teaches-us-about-home", destination: "/odisha/what-travel-teaches-us-about-home", permanent: true },
      { source: "/essays/what-was-i-wrong-about", destination: "/philosophy/what-was-i-wrong-about", permanent: true },
      { source: "/essays/why-every-sector-learns-observability-the-hard-way", destination: "/future-of-work/why-every-sector-learns-observability-the-hard-way", permanent: true },
      { source: "/essays/why-executive-hires-fail", destination: "/hiring/why-executive-hires-fail", permanent: true },
      { source: "/essays/why-executive-searches-fail", destination: "/hiring/why-executive-searches-fail", permanent: true },
      { source: "/essays/why-food-matters-more-than-we-think", destination: "/travel/why-food-matters-more-than-we-think", permanent: true },
      { source: "/essays/why-frequent-travelers-think-differently", destination: "/travel/why-frequent-travelers-think-differently", permanent: true },
      { source: "/essays/why-global-companies-should-consider-odisha", destination: "/odisha/why-global-companies-should-consider-odisha", permanent: true },
      { source: "/essays/why-global-companies-should-hire-from-india", destination: "/india/why-global-companies-should-hire-from-india", permanent: true },
      { source: "/essays/why-hiring-is-becoming-infrastructure", destination: "/hiring/why-hiring-is-becoming-infrastructure", permanent: true },
      { source: "/essays/why-i-build", destination: "/entrepreneurship/why-i-build", permanent: true },
      { source: "/essays/why-i-keep-talking-about-odisha", destination: "/odisha/why-i-keep-talking-about-odisha", permanent: true },
      { source: "/essays/why-indias-moment-is-now", destination: "/india/why-indias-moment-is-now", permanent: true },
      { source: "/essays/why-indias-scale-matters", destination: "/india/why-indias-scale-matters", permanent: true },
      { source: "/essays/why-infrastructure-matters-more-than-headlines", destination: "/india/why-infrastructure-matters-more-than-headlines", permanent: true },
      { source: "/essays/why-is-odisha-underrated", destination: "/odisha/why-is-odisha-underrated", permanent: true },
      { source: "/essays/why-most-founders-quit-too-early", destination: "/entrepreneurship/why-most-founders-quit-too-early", permanent: true },
      { source: "/essays/why-odisha-matters", destination: "/odisha/why-odisha-matters", permanent: true },
      { source: "/essays/why-places-like-kalahandi-produce-determined-people", destination: "/kalahandi/why-places-like-kalahandi-produce-determined-people", permanent: true },
      { source: "/essays/why-should-companies-hire-from-odisha", destination: "/odisha/why-should-companies-hire-from-odisha", permanent: true },
      { source: "/essays/why-talented-people-stay-unnoticed", destination: "/future-of-work/why-talented-people-stay-unnoticed", permanent: true },
      { source: "/essays/why-your-vp-search-stalled-at-week-ten", destination: "/hiring/why-your-vp-search-stalled-at-week-ten", permanent: true },
      { source: "/essays/world-staffing-leader", destination: "/hiring/world-staffing-leader", permanent: true },
      // /thinking → /the-map
      { source: "/thinking", destination: "/the-map", permanent: true },
    ];
  },

  async rewrites() {
    return [
      { source: "/index", destination: "/all" },
    ];
  },

  async headers() {
    const csp = [
      "default-src 'self'",
      // Next.js needs unsafe-inline for hydration scripts; JSON-LD scripts also require it
      "script-src 'self' 'unsafe-inline'",
      // Tailwind inline styles + Google Fonts CSS
      "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
      // Unsplash (essays), Sanity CDN (recognition page), Google Fonts files, data URIs
      "img-src 'self' https://images.unsplash.com https://cdn.sanity.io data: blob:",
      // Google Fonts files
      "font-src 'self' https://fonts.gstatic.com data:",
      // API routes only
      "connect-src 'self'",
      // No iframes
      "frame-src 'none'",
      "frame-ancestors 'none'",
      // Prevent base tag hijacking
      "base-uri 'self'",
      // Forms only post to same origin
      "form-action 'self'",
      // Upgrade HTTP to HTTPS
      "upgrade-insecure-requests",
    ].join("; ");

    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-XSS-Protection", value: "1; mode=block" },
          { key: "Content-Security-Policy", value: csp },
          // 1-year HSTS, include subdomains
          { key: "Strict-Transport-Security", value: "max-age=31536000; includeSubDomains" },
          // Send full URL for same-origin, origin only for cross-origin
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          // Disable browser features not used by the site
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=(), browsing-topics=()" },
        ],
      },
    ];
  },
};

export default nextConfig;
