import { NextResponse } from "next/server";

const INDEXNOW_KEY = "0463c309f62647a89d1075955c121505";
const SITE_HOST = "www.manasmajhi.com";

// Pre-computed URL list — avoids internal sitemap fetch (which causes serverless timeout)
const SITE_URLS = [
  "https://www.manasmajhi.com/",
  "https://www.manasmajhi.com/start-here",
  "https://www.manasmajhi.com/writing",
  "https://www.manasmajhi.com/frameworks",
  "https://www.manasmajhi.com/about",
  "https://www.manasmajhi.com/work",
  "https://www.manasmajhi.com/timeline",
  "https://www.manasmajhi.com/elsewhere",
  "https://www.manasmajhi.com/recognition",
  "https://www.manasmajhi.com/library",
  "https://www.manasmajhi.com/all",
  "https://www.manasmajhi.com/work-with-me",
  "https://www.manasmajhi.com/whitepaper",
  "https://www.manasmajhi.com/opportunity",
  "https://www.manasmajhi.com/future-of-work",
  "https://www.manasmajhi.com/india",
  "https://www.manasmajhi.com/odisha",
  "https://www.manasmajhi.com/kalahandi",
  "https://www.manasmajhi.com/travel",
  "https://www.manasmajhi.com/entrepreneurship",
  "https://www.manasmajhi.com/philosophy",
  "https://www.manasmajhi.com/hiring",
  "https://www.manasmajhi.com/odisha/a-love-letter-to-odisha",
  "https://www.manasmajhi.com/philosophy/active-waiting",
  "https://www.manasmajhi.com/future-of-work/ai-and-education",
  "https://www.manasmajhi.com/future-of-work/ai-and-hiring",
  "https://www.manasmajhi.com/future-of-work/ai-and-human-potential",
  "https://www.manasmajhi.com/future-of-work/ai-and-india",
  "https://www.manasmajhi.com/opportunity/ai-and-opportunity",
  "https://www.manasmajhi.com/odisha/berhampur",
  "https://www.manasmajhi.com/odisha/beyond-gdp-what-a-developed-odisha-must-be-answerable-for",
  "https://www.manasmajhi.com/odisha/bhubaneswar",
  "https://www.manasmajhi.com/philosophy/books-that-changed-my-thinking",
  "https://www.manasmajhi.com/hiring/broken-hiring-systems-and-the-opportunity-gap",
  "https://www.manasmajhi.com/odisha/building-a-global-business-from-odisha",
  "https://www.manasmajhi.com/india/building-for-a-billion-people",
  "https://www.manasmajhi.com/kalahandi/building-from-kalahandi",
  "https://www.manasmajhi.com/entrepreneurship/building-through-uncertainty",
  "https://www.manasmajhi.com/hiring/ceo-search",
  "https://www.manasmajhi.com/hiring/cfo-search",
  "https://www.manasmajhi.com/hiring/chief-of-staff",
  "https://www.manasmajhi.com/hiring/cmo-search",
  "https://www.manasmajhi.com/frameworks/compounding-failure-loop",
  "https://www.manasmajhi.com/philosophy/contentment-vs-success",
  "https://www.manasmajhi.com/hiring/cto-recruitment-india",
  "https://www.manasmajhi.com/hiring/cto-search",
  "https://www.manasmajhi.com/odisha/cuttack",
  "https://www.manasmajhi.com/india/digital-public-infrastructure",
  "https://www.manasmajhi.com/hiring/dubai",
  "https://www.manasmajhi.com/odisha/eastern-indias-biopharma-gap",
  "https://www.manasmajhi.com/kalahandi/entrepreneurship-in-kalahandi",
  "https://www.manasmajhi.com/frameworks/failure-prediction-system",
  "https://www.manasmajhi.com/hiring/fintech-cto-recruitment",
  "https://www.manasmajhi.com/hiring/fintech",
  "https://www.manasmajhi.com/frameworks/first-generation-founder-framework",
  "https://www.manasmajhi.com/opportunity/first-generation-professionals-and-opportunity",
  "https://www.manasmajhi.com/hiring/forty-one-days",
  "https://www.manasmajhi.com/entrepreneurship/founder-lessons-from-the-frontline",
  "https://www.manasmajhi.com/hiring/gen-ai-wont-replace-recruiters",
  "https://www.manasmajhi.com/frameworks/geography-advantage-framework",
  "https://www.manasmajhi.com/future-of-work/global-talent-how-borders-are-dissolving",
  "https://www.manasmajhi.com/kalahandi/growing-up-in-an-odia-medium-school",
  "https://www.manasmajhi.com/kalahandi/growing-up-in-kalahandi",
  "https://www.manasmajhi.com/hiring/gtm",
  "https://www.manasmajhi.com/entrepreneurship/hackernoon-startup-of-the-year-2023",
  "https://www.manasmajhi.com/philosophy/have-they-done-this-before",
  "https://www.manasmajhi.com/philosophy/healthspan-vs-lifespan",
  "https://www.manasmajhi.com/frameworks/hiring-slo-framework",
  "https://www.manasmajhi.com/frameworks/hiring-system-health",
  "https://www.manasmajhi.com/india/how-4g-changed-india",
  "https://www.manasmajhi.com/hiring/how-executive-search-works",
  "https://www.manasmajhi.com/philosophy/how-i-think-about-learning",
  "https://www.manasmajhi.com/philosophy/how-i-think-about-people",
  "https://www.manasmajhi.com/philosophy/how-i-think-about-systems",
  "https://www.manasmajhi.com/hiring/how-long-does-executive-search-take",
  "https://www.manasmajhi.com/opportunity/how-opportunity-compounds",
  "https://www.manasmajhi.com/opportunity/how-to-create-opportunity-for-others",
  "https://www.manasmajhi.com/hiring/how-to-evaluate-executive-candidates",
  "https://www.manasmajhi.com/hiring/how-to-find-cto-india",
  "https://www.manasmajhi.com/hiring/how-to-write-an-executive-role-brief",
  "https://www.manasmajhi.com/opportunity/improving-lives-with-new-opportunities",
  "https://www.manasmajhi.com/india/india-vs-china-talent",
  "https://www.manasmajhi.com/hiring/india",
  "https://www.manasmajhi.com/entrepreneurship/indian-achievers-award-2022",
  "https://www.manasmajhi.com/india/indias-ai-opportunity",
  "https://www.manasmajhi.com/india/indias-future-in-10-years",
  "https://www.manasmajhi.com/india/indias-greatest-asset-is-its-people",
  "https://www.manasmajhi.com/india/indias-infrastructure-revolution",
  "https://www.manasmajhi.com/india/indias-startup-ecosystem",
  "https://www.manasmajhi.com/india/indias-technology-ecosystem",
  "https://www.manasmajhi.com/frameworks/intelligence-hiring-system",
  "https://www.manasmajhi.com/hiring/intelligence-hiring-vs-traditional-hiring",
  "https://www.manasmajhi.com/hiring/is-ai-replacing-executive-recruiters",
  "https://www.manasmajhi.com/odisha/is-bhubaneswar-a-tech-hub",
  "https://www.manasmajhi.com/odisha/is-odisha-good-for-startups",
  "https://www.manasmajhi.com/odisha/is-odisha-safe-to-visit",
  "https://www.manasmajhi.com/kalahandi/kalahandi-and-the-opportunity-gap",
  "https://www.manasmajhi.com/india/karnataka",
  "https://www.manasmajhi.com/travel/langkawi-the-day-everything-looked-perfect",
  "https://www.manasmajhi.com/philosophy/learning-from-people",
  "https://www.manasmajhi.com/travel/lessons-from-airports",
  "https://www.manasmajhi.com/kalahandi/lessons-from-rural-india",
  "https://www.manasmajhi.com/philosophy/long-term-thinking-in-a-short-term-world",
  "https://www.manasmajhi.com/india/maharashtra",
  "https://www.manasmajhi.com/frameworks/mandate-recovery-framework",
  "https://www.manasmajhi.com/philosophy/midnight-calls-and-invisible-sacrifices",
  "https://www.manasmajhi.com/india/nationalism-vs-patriotism",
  "https://www.manasmajhi.com/opportunity/networks-are-not-networking",
  "https://www.manasmajhi.com/odisha/odisha-ai-ecosystem",
  "https://www.manasmajhi.com/odisha/odisha-economy",
  "https://www.manasmajhi.com/odisha/odisha-infrastructure",
  "https://www.manasmajhi.com/odisha/odisha-manufacturing",
  "https://www.manasmajhi.com/odisha/odisha-startups",
  "https://www.manasmajhi.com/odisha/odisha-talent",
  "https://www.manasmajhi.com/odisha/odisha-technology-ecosystem",
  "https://www.manasmajhi.com/odisha/odisha-tourism",
  "https://www.manasmajhi.com/odisha/odisha-transport-vision",
  "https://www.manasmajhi.com/odisha/odisha-vs-gujarat",
  "https://www.manasmajhi.com/odisha/odisha-vs-karnataka",
  "https://www.manasmajhi.com/odisha/odishas-resource-trap",
  "https://www.manasmajhi.com/odisha/odishas-untapped-potential",
  "https://www.manasmajhi.com/philosophy/on-identity-and-where-you-come-from",
  "https://www.manasmajhi.com/philosophy/on-success-what-it-actually-means",
  "https://www.manasmajhi.com/philosophy/one-year-later",
  "https://www.manasmajhi.com/opportunity/opportunity-and-mobility-in-modern-india",
  "https://www.manasmajhi.com/opportunity/opportunity-changes-lives",
  "https://www.manasmajhi.com/frameworks/opportunity-framework",
  "https://www.manasmajhi.com/opportunity/opportunity-gaps",
  "https://www.manasmajhi.com/opportunity/opportunity-in-india",
  "https://www.manasmajhi.com/opportunity/opportunity-in-rural-india",
  "https://www.manasmajhi.com/frameworks/opportunity-mobility-framework",
  "https://www.manasmajhi.com/philosophy/people-are-more-similar-than-different",
  "https://www.manasmajhi.com/travel/places-that-changed-how-i-think",
  "https://www.manasmajhi.com/philosophy/questions-i-keep-returning-to",
  "https://www.manasmajhi.com/hiring/remote-cto-hiring",
  "https://www.manasmajhi.com/india/remote-work-and-india",
  "https://www.manasmajhi.com/future-of-work/remote-work-what-we-know",
  "https://www.manasmajhi.com/hiring/remote",
  "https://www.manasmajhi.com/hiring/retained-vs-contingency-search",
  "https://www.manasmajhi.com/odisha/rourkela",
  "https://www.manasmajhi.com/hiring/saas-cto-search",
  "https://www.manasmajhi.com/hiring/saas",
  "https://www.manasmajhi.com/hiring/sales-account-management",
  "https://www.manasmajhi.com/odisha/sambalpur",
  "https://www.manasmajhi.com/odisha/showing-friends-around-odisha",
  "https://www.manasmajhi.com/hiring/singapore",
  "https://www.manasmajhi.com/future-of-work/skills-vs-degrees",
  "https://www.manasmajhi.com/india/state-capacity-is-the-ultimate-competitive-advantage",
  "https://www.manasmajhi.com/travel/stories-from-the-road",
  "https://www.manasmajhi.com/hiring/strategy-consulting",
  "https://www.manasmajhi.com/opportunity/systems-that-create-opportunity",
  "https://www.manasmajhi.com/opportunity/systems-that-destroy-opportunity",
  "https://www.manasmajhi.com/kalahandi/talent-from-small-town-india",
  "https://www.manasmajhi.com/opportunity/talent-is-evenly-distributed",
  "https://www.manasmajhi.com/frameworks/talent-signal-framework",
  "https://www.manasmajhi.com/india/tamil-nadu",
  "https://www.manasmajhi.com/india/telangana",
  "https://www.manasmajhi.com/hiring/the-50-day-executive-search",
  "https://www.manasmajhi.com/future-of-work/the-autonomous-hiring-era",
  "https://www.manasmajhi.com/kalahandi/the-childhood-lessons-i-still-use-every-day",
  "https://www.manasmajhi.com/hiring/the-cost-of-hiring-the-wrong-leader",
  "https://www.manasmajhi.com/philosophy/the-evolution-of-my-thinking",
  "https://www.manasmajhi.com/entrepreneurship/the-first-international-client",
  "https://www.manasmajhi.com/hiring/the-four-ways-hiring-infrastructure-fails",
  "https://www.manasmajhi.com/hiring/the-future-belongs-to-operational-intelligence",
  "https://www.manasmajhi.com/hiring/the-future-of-executive-search",
  "https://www.manasmajhi.com/india/the-future-of-indian-cities",
  "https://www.manasmajhi.com/kalahandi/the-future-of-kalahandi",
  "https://www.manasmajhi.com/odisha/the-future-of-odisha",
  "https://www.manasmajhi.com/opportunity/the-geography-of-opportunity",
  "https://www.manasmajhi.com/india/the-india-i-see",
  "https://www.manasmajhi.com/opportunity/the-information-gap",
  "https://www.manasmajhi.com/entrepreneurship/the-joy-of-growing-something-from-scratch",
  "https://www.manasmajhi.com/kalahandi/the-kalahandi-most-people-never-see",
  "https://www.manasmajhi.com/india/the-most-underrated-innovation-in-india",
  "https://www.manasmajhi.com/future-of-work/the-next-decade-of-work",
  "https://www.manasmajhi.com/opportunity/the-obligation-that-comes-with-getting-through-the-door",
  "https://www.manasmajhi.com/entrepreneurship/the-reality-behind-overnight-success",
  "https://www.manasmajhi.com/future-of-work/the-recruiter-isnt-being-replaced",
  "https://www.manasmajhi.com/hiring/the-rise-of-hiring-system-health",
  "https://www.manasmajhi.com/india/tier-2-tier-3-cities-india",
  "https://www.manasmajhi.com/philosophy/tourism-as-an-economic-engine",
  "https://www.manasmajhi.com/travel/travel-as-a-learning-system",
  "https://www.manasmajhi.com/hiring/uk",
  "https://www.manasmajhi.com/hiring/usa",
  "https://www.manasmajhi.com/hiring/vp-engineering-india",
  "https://www.manasmajhi.com/hiring/vp-engineering",
  "https://www.manasmajhi.com/hiring/vp-product-search",
  "https://www.manasmajhi.com/hiring/vp-sales-search",
  "https://www.manasmajhi.com/hiring/web3-leadership-search",
  "https://www.manasmajhi.com/hiring/web3",
  "https://www.manasmajhi.com/entrepreneurship/what-am-i-building",
  "https://www.manasmajhi.com/philosophy/what-am-i-learning",
  "https://www.manasmajhi.com/future-of-work/what-automation-cannot-replace",
  "https://www.manasmajhi.com/philosophy/what-changed-my-mind-this-year",
  "https://www.manasmajhi.com/hiring/what-does-executive-search-cost",
  "https://www.manasmajhi.com/travel/what-does-travel-teach-you-about-yourself",
  "https://www.manasmajhi.com/india/what-good-policy-actually-looks-like",
  "https://www.manasmajhi.com/travel/what-home-looks-like-from-far-away",
  "https://www.manasmajhi.com/philosophy/what-i-believe",
  "https://www.manasmajhi.com/odisha/what-industries-are-growing-in-odisha",
  "https://www.manasmajhi.com/kalahandi/what-is-kalahandi",
  "https://www.manasmajhi.com/odisha/what-is-odisha-known-for",
  "https://www.manasmajhi.com/opportunity/what-is-opportunity",
  "https://www.manasmajhi.com/hiring/what-is-retained-executive-search",
  "https://www.manasmajhi.com/odisha/what-is-the-future-of-bhubaneswar",
  "https://www.manasmajhi.com/kalahandi/what-kalahandi-taught-me-about-human-nature",
  "https://www.manasmajhi.com/kalahandi/what-kalahandi-taught-me-about-opportunity",
  "https://www.manasmajhi.com/kalahandi/what-kalahandi-taught-me-about-resilience",
  "https://www.manasmajhi.com/odisha/what-kalinga-knew-about-the-indian-ocean",
  "https://www.manasmajhi.com/hiring/what-makes-a-great-executive-brief",
  "https://www.manasmajhi.com/future-of-work/what-makes-great-talent-stand-out",
  "https://www.manasmajhi.com/opportunity/what-missed-opportunity-costs",
  "https://www.manasmajhi.com/odisha/what-odisha-gets-right",
  "https://www.manasmajhi.com/hiring/what-three-thousand-a-month-in-recruiting-tools-actually-costs-you",
  "https://www.manasmajhi.com/hiring/what-to-expect-from-executive-search",
  "https://www.manasmajhi.com/travel/what-travel-has-taught-me",
  "https://www.manasmajhi.com/travel/what-travel-teaches-us-about-home",
  "https://www.manasmajhi.com/philosophy/what-was-i-wrong-about",
  "https://www.manasmajhi.com/future-of-work/why-every-sector-learns-observability-the-hard-way",
  "https://www.manasmajhi.com/hiring/why-executive-hires-fail",
  "https://www.manasmajhi.com/hiring/why-executive-searches-fail",
  "https://www.manasmajhi.com/travel/why-food-matters-more-than-we-think",
  "https://www.manasmajhi.com/travel/why-frequent-travelers-think-differently",
  "https://www.manasmajhi.com/odisha/why-global-companies-should-consider-odisha",
  "https://www.manasmajhi.com/india/why-global-companies-should-hire-from-india",
  "https://www.manasmajhi.com/hiring/why-hiring-is-becoming-infrastructure",
  "https://www.manasmajhi.com/entrepreneurship/why-i-build",
  "https://www.manasmajhi.com/odisha/why-i-keep-talking-about-odisha",
  "https://www.manasmajhi.com/india/why-indias-moment-is-now",
  "https://www.manasmajhi.com/india/why-indias-scale-matters",
  "https://www.manasmajhi.com/india/why-infrastructure-matters-more-than-headlines",
  "https://www.manasmajhi.com/odisha/why-is-odisha-underrated",
  "https://www.manasmajhi.com/entrepreneurship/why-most-founders-quit-too-early",
  "https://www.manasmajhi.com/odisha/why-odisha-matters",
  "https://www.manasmajhi.com/kalahandi/why-places-like-kalahandi-produce-determined-people",
  "https://www.manasmajhi.com/odisha/why-should-companies-hire-from-odisha",
  "https://www.manasmajhi.com/future-of-work/why-talented-people-stay-unnoticed",
  "https://www.manasmajhi.com/hiring/why-your-vp-search-stalled-at-week-ten",
  "https://www.manasmajhi.com/hiring/world-staffing-leader",
];

export async function GET(req: Request) {
  // Vercel cron jobs send Authorization: Bearer <CRON_SECRET>
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Submit to IndexNow (Bing)
  const body = {
    host: SITE_HOST,
    key: INDEXNOW_KEY,
    keyLocation: `https://${SITE_HOST}/${INDEXNOW_KEY}.txt`,
    urlList: SITE_URLS,
  };

  const indexNowRes = await fetch("https://www.bing.com/indexnow", {
    method: "POST",
    headers: { "Content-Type": "application/json; charset=utf-8" },
    body: JSON.stringify(body),
  });

  return NextResponse.json({
    success: indexNowRes.ok,
    status: indexNowRes.status,
    urlCount: SITE_URLS.length,
    submittedAt: new Date().toISOString(),
  });
}
